owner: m-akbarfauzi
repo: uptime

sites:
  - name: Tasikmalaya Kota
    url: https://tasikmalayakota.go.id.com
  - name: Portal
    url: https://portal.tasikmalayakota.go.id
  - name: Diskominfo
    url: https://diskominfo.tasikmalayakota.go.id
  - name: SmartKelurahan
    url: https://smartkelurahan.tasikmalayakota.go.id

status-website:
  cname: check.tasikmalayakota.go.id
  # baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Uptime** Kota Tasikmalaya."
  introMessage: This is a monitoring website status page that uses **real-time** data.
  navbar:
    # - title: Status
    #   href: /
    # - title: GitHub
    #   href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

