owner: m-akbarfauzi
repo: uptime

sites:
  - name: Tasikmalaya Kota
    url: https://tasikmalayakota.go.id
  - name: Portal
    url: https://portal.tasikmalayakota.go.id
  - name: Email
    url: http://email.tasikmalayakota.go.id
  - name: Suresman
    url: https://suresman.tasikmalayakota.go.id
  - name: Sipentas v.2 (Perizinan Online)
    url: http://new.sipentas.tasikmalayakota.go.id
  - name: Dinas Komunikasi dan Informatika
    url: https://diskominfo.tasikmalayakota.go.id
  - name: Beta
    url: https://beta.tasikmalayakota.go.id
  - name: Andimas
    url: http://andimas.tasikmalayakota.go.id
  - name: Arsip Dinamis
    url: http://arsipdinamis.tasikmalayakota.go.id
  - name: ATCS
    url: http://atcs.tasikmalayakota.go.id
  - name: Ayo Belajar
    url: http://ayobelajar.tasikmalayakota.go.id
  - name: Bappelitbangda
    url: http://bappelitbangda.tasikmalayakota.go.id
  - name: Bisma
    url: http://bisma.tasikmalayakota.go.id
  - name: BKPSDM
    url: http://bkppd.tasikmalayakota.go.id
  - name: BPBD
    url: http://bpbd.tasikmalayakota.go.id
  - name: BPKAD
    url: http://bpkad.tasikmalayakota.go.id
  - name: Bapenda
    url: http://bpprd.tasikmalayakota.go.id
  - name: Command Center
    url: https://cc.tasikmalayakota.go.id/login
  - name: CSR
    url: http://csr.tasikmalayakota.go.id
  - name: Dekranasda
    url: http://dekranasda.tasikmalayakota.go.id
  - name: Disdukcapil
    url: http://dinasdukcapil.tasikmalayakota.go.id
  - name: Dinas Kesehatan
    url: http://dinkes.tasikmalayakota.go.id
  - name: Dipusipda
    url: http://dipusipda.tasikmalayakota.go.id
  - name: Dinas Pendidikan
    url: http://disdik.tasikmalayakota.go.id
  - name: Dinas Perhubungan
    url: http://dishub.tasikmalayakota.go.id
  - name: Dinas Tenaga Kerja
    url: http://disnaker.tasikmalayakota.go.id
  - name: Disperawaskim
    url: http://disperawaskim.tasikmalayakota.go.id
  - name: Disporabudpar
    url: http://disporabudpar.tasikmalayakota.go.id
  - name: Aplikasi Manajemen Surat
    url: http://disposisi.tasikmalayakota.go.id
  - name: DPMPTSP
    url: http://dpmptsp.tasikmalayakota.go.id
  - name: E-Kinerja
    url: http://ekinerja.tasikmalayakota.go.id

status-website:
  cname: check.tasikmalayakota.go.id
  # baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime Website
  introTitle: "**Uptime** Kota Tasikmalaya."
  introMessage: This is a monitoring website status page that uses **real-time** data.
  navbar:
    - title: Status
      href: /
    # - title: GitHub
    #   href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
